import type { Metadata } from 'next';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '@/app/components/ThemeRegistry';
import MenuAppBar from '@/app/components/AppBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeRegistry>
          <MenuAppBar />
          <Box sx={{ display: 'flex', width: '100%' }}>
            <Box sx={{ width: '8.33%' }} />
            <Box sx={{ width: '83.33%' }}>{children}</Box>
            <Box sx={{ width: '8.33%' }} />
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
}
